"""
Step 2b — compute YOLO greedy-IoU metrics on crowded and sparse subsets.

Inputs:
- runs/yolo_greedy_eval/predictions_test_yolo_greedy.json generated by
  scripts/two_stage_baseline/evaluate_yolo_greedy_iou.py --split test --skip_step4
- split list files from step1.

Method:
- Reuse subset evaluation helpers from scripts/crowded_field/step3_two_stage_subset_metrics.py.
- Reuse greedy IoU matching semantics from scripts/two_stage_baseline/step4_evaluate_two_stage.py.
- Write one JSON report per subset.

Run from project root:
  python3 scripts/crowded_field/step2b_yolo_subset_greedy_metrics.py
"""

from __future__ import annotations

# Dynamic import to reuse subset evaluation from step3 without code duplication.
import importlib.util
# JSON IO for predictions and output reports.
import json
# stderr + exit codes for CLI failures.
import sys
from pathlib import Path
from typing import Dict, Set

# Repository root and file locations used across the crowded-field pipeline.
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
PRED_PATH = PROJECT_ROOT / "runs" / "yolo_greedy_eval" / "predictions_test_yolo_greedy.json"
SPLITS_DIR = PROJECT_ROOT / "data" / "splits"
TXT_CROWDED = SPLITS_DIR / "test_crowded.txt"
TXT_SPARSE = SPLITS_DIR / "test_sparse.txt"
OUT_DIR = PROJECT_ROOT / "runs" / "detect" / "crowded_field_eval"
OUT_C = OUT_DIR / "yolo_crowded_greedy_results.json"
OUT_S = OUT_DIR / "yolo_sparse_greedy_results.json"


def load_step3_subset_module():
    # Reuse evaluate_subset() from step3 to keep one metric implementation.
    # Reference: scripts/crowded_field/step3_two_stage_subset_metrics.py
    path = PROJECT_ROOT / "scripts" / "crowded_field" / "step3_two_stage_subset_metrics.py"
    spec = importlib.util.spec_from_file_location("step3_two_stage_subset_metrics", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load module spec for {path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def stems_from_list_file(list_path: Path) -> Set[str]:
    # Read split list and keep just image stems for fast membership checks.
    stems: Set[str] = set()
    with open(list_path) as f:
        for line in f:
            line = line.strip()
            if line:
                stems.add(Path(line).stem)
    return stems


def filter_images(images: Dict, allowed_stems: Set[str]) -> Dict:
    # Keep only prediction entries whose filename stem belongs to the subset list.
    out = {}
    for rel_key, entry in images.items():
        if Path(rel_key).stem in allowed_stems:
            out[rel_key] = entry
    return out


def to_json_report(subset: str, res_tuple) -> dict:
    # Convert evaluate_subset() tuple into named JSON fields for downstream step4 summary.
    (
        det_p,
        det_r,
        det_f1,
        e2e_p,
        e2e_r,
        e2e_f1,
        cls_acc,
        n_img,
        p0,
        r0,
        f1_0,
        p1,
        r1,
        f1_1,
        macro_f1,
    ) = res_tuple
    return {
        "subset": subset,
        "images_evaluated": n_img,
        "detection_precision": det_p,
        "detection_recall": det_r,
        "detection_f1": det_f1,
        "end_to_end_precision": e2e_p,
        "end_to_end_recall": e2e_r,
        "end_to_end_f1": e2e_f1,
        "class_label_accuracy_matched": cls_acc,
        "per_class_parasitized_precision": p0,
        "per_class_parasitized_recall": r0,
        "per_class_parasitized_f1": f1_0,
        "per_class_uninfected_precision": p1,
        "per_class_uninfected_recall": r1,
        "per_class_uninfected_f1": f1_1,
        "per_class_macro_f1": macro_f1,
    }


def main() -> None:
    # Require YOLO greedy predictions exported by evaluate_yolo_greedy_iou.py.
    if not PRED_PATH.exists():
        print(f"ERROR: Missing YOLO greedy predictions: {PRED_PATH}", file=sys.stderr)
        print("Run: python3 scripts/two_stage_baseline/evaluate_yolo_greedy_iou.py --split test --conf 0.25 --skip_step4")
        sys.exit(1)
    # Require crowded/sparse split lists generated by step1.
    if not TXT_CROWDED.exists() or not TXT_SPARSE.exists():
        print("ERROR: Missing split files. Run crowded_field step1 first.", file=sys.stderr)
        sys.exit(1)

    # Load subset evaluation helpers and fixed IoU used in crowded-field protocol.
    mod = load_step3_subset_module()
    iou = 0.5

    # Read full prediction dictionary from YOLO greedy export.
    with open(PRED_PATH) as f:
        data = json.load(f)
    images_all = data.get("images", {})
    if not images_all:
        print("ERROR: predictions JSON has no images.", file=sys.stderr)
        sys.exit(1)

    # Build stem sets and filter JSON images map for each subset.
    stems_c = stems_from_list_file(TXT_CROWDED)
    stems_s = stems_from_list_file(TXT_SPARSE)
    img_c = filter_images(images_all, stems_c)
    img_s = filter_images(images_all, stems_s)

    # Evaluate each subset using step3 helper + step4 matching logic.
    # Reference: scripts/two_stage_baseline/step4_evaluate_two_stage.py
    res_c = mod.evaluate_subset(mod.load_step4_module(), img_c, "yolo_crowded_greedy", iou)
    res_s = mod.evaluate_subset(mod.load_step4_module(), img_s, "yolo_sparse_greedy", iou)

    # Save one machine-readable JSON per subset.
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    report_c = to_json_report("crowded", res_c)
    report_s = to_json_report("sparse", res_s)
    OUT_C.write_text(json.dumps(report_c, indent=2) + "\n")
    OUT_S.write_text(json.dumps(report_s, indent=2) + "\n")

    print("YOLO greedy crowded/sparse results")
    print("=" * 40)
    print(f"Crowded end-to-end F1: {report_c['end_to_end_f1']:.4f} | Detection F1: {report_c['detection_f1']:.4f}")
    print(f"Sparse  end-to-end F1: {report_s['end_to_end_f1']:.4f} | Detection F1: {report_s['detection_f1']:.4f}")
    print(f"Saved: {OUT_C}")
    print(f"Saved: {OUT_S}")


if __name__ == "__main__":
    main()
