"""
Step 4: Load YOLO and two-stage robustness CSVs, compute performance drop vs clean, print and save tables.

Drop = metric on corrupted − metric on clean (e.g. Clean F1 0.89 → Blur F1 0.80 → Drop −0.09).

Run from project root (after step2 and step3):
  python3 scripts/robustness/step4_report_robustness.py

Notes:
- "Drop" is always computed relative to the clean condition from the same CSV.
- Output is a long-form summary CSV so results can be reused directly in tables
  and plotting scripts without re-parsing console output.
"""

import csv
from pathlib import Path

# Project root anchor so script is runnable from any working directory.
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
# Folder where robustness CSV artifacts are written by Steps 2 and 3.
RUNS_ROBUSTNESS = PROJECT_ROOT / "runs" / "robustness"
# Input metrics from end-to-end YOLO robustness run.
YOLO_CSV = RUNS_ROBUSTNESS / "yolo_robustness_metrics.csv"
# Input metrics from two-stage robustness run.
TWO_STAGE_CSV = RUNS_ROBUSTNESS / "two_stage_robustness_metrics.csv"
# Long-form merged output used for plotting/tables in chapter writing.
OUT_SUMMARY = RUNS_ROBUSTNESS / "robustness_drops_summary.csv"


def load_csv(path: Path) -> list[dict]:
    # Return empty list if file is missing so caller can handle gracefully.
    if not path.exists():
        return []
    # Read CSV rows as dictionaries keyed by header names.
    with open(path, newline="") as f:
        return list(csv.DictReader(f))


def get_clean_row(rows: list[dict]) -> dict | None:
    # "clean" is the baseline condition used to compute drops.
    for r in rows:
        if r.get("condition") == "clean":
            return r
    return None


def main():
    # Load metrics generated by Step 2 (YOLO) and Step 3 (two-stage).
    yolo_rows = load_csv(YOLO_CSV)
    two_stage_rows = load_csv(TWO_STAGE_CSV)

    if not yolo_rows and not two_stage_rows:
        print(f"No metrics found. Run step2 and step3 first.")
        print(f"  {YOLO_CSV}")
        print(f"  {TWO_STAGE_CSV}")
        return

    yolo_clean = get_clean_row(yolo_rows)
    two_stage_clean = get_clean_row(two_stage_rows)

    # Build unified condition list (clean + all corruptions from both CSVs).
    all_conditions = set()
    for r in yolo_rows:
        all_conditions.add(r["condition"])
    for r in two_stage_rows:
        all_conditions.add(r["condition"])
    all_conditions = ["clean"] + sorted(c for c in all_conditions if c != "clean")

    # Long-form rows written to OUT_SUMMARY for reuse in plots/tables.
    summary_rows = []

    # YOLO branch: report F1/mAP50 and compute drop vs clean F1.
    if yolo_rows and yolo_clean:
        print("=" * 60)
        print("End-to-end YOLO (F1, mAP50)")
        print("=" * 60)
        print(f"{'Condition':<25} {'Clean F1':<10} {'F1':<10} {'Drop':<10} {'mAP50':<10}")
        print("-" * 60)
        for cond in all_conditions:
            row = next((r for r in yolo_rows if r["condition"] == cond), None)
            if not row:
                continue
            f1 = float(row.get("F1", 0))
            m50 = float(row.get("mAP50", 0))
            # Reference (drop definition): corrupted metric - clean metric.
            clean_f1 = float(yolo_clean.get("F1", 0))
            drop = f1 - clean_f1 if cond != "clean" else 0.0
            print(f"{cond:<25} {clean_f1:<10.4f} {f1:<10.4f} {drop:+.4f}    {m50:<10.4f}")
            summary_rows.append({
                "model": "yolo",
                "condition": cond,
                "metric": "F1",
                "value": f1,
                "clean_value": clean_f1,
                "drop": drop,
            })

    # Two-stage branch: report E2E F1 / Det F1 / Cls accuracy and drop vs clean E2E.
    if two_stage_rows and two_stage_clean:
        print()
        print("=" * 60)
        print("Two-stage (End-to-end F1, Detection F1, Cls Accuracy)")
        print("=" * 60)
        print(f"{'Condition':<25} {'Clean E2E F1':<12} {'E2E F1':<10} {'Drop':<10} {'Det F1':<10} {'Cls Acc':<10}")
        print("-" * 60)
        for cond in all_conditions:
            row = next((r for r in two_stage_rows if r["condition"] == cond), None)
            if not row:
                continue
            e2e = float(row.get("e2e_f1", 0))
            det_f1 = float(row.get("detection_f1", 0))
            acc = float(row.get("cls_accuracy", 0))
            # Reference (drop definition): corrupted metric - clean metric.
            clean_e2e = float(two_stage_clean.get("e2e_f1", 0))
            drop = e2e - clean_e2e if cond != "clean" else 0.0
            print(f"{cond:<25} {clean_e2e:<12.4f} {e2e:<10.4f} {drop:+.4f}    {det_f1:<10.4f} {acc:<10.4f}")
            summary_rows.append({
                "model": "two_stage",
                "condition": cond,
                "metric": "e2e_f1",
                "value": e2e,
                "clean_value": clean_e2e,
                "drop": drop,
            })

    # Save merged long-form summary for reproducible chapter reporting.
    RUNS_ROBUSTNESS.mkdir(parents=True, exist_ok=True)
    with open(OUT_SUMMARY, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["model", "condition", "metric", "value", "clean_value", "drop"])
        w.writeheader()
        w.writerows(summary_rows)
    print()
    print(f"Summary saved: {OUT_SUMMARY}")
    print("That makes robustness easy to discuss.")


if __name__ == "__main__":
    main()
